services:
  - type: web
    name: metabase-light-render
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    plan: free
    autoDeploy: true
    envVars:
      - key: MB_JETTY_PORT
        value: "3000"
      - key: PORT
        value: "3000"
    ports:
      - port: 3000
