services:
  - type: web
    name: metabase-light-render
    env: docker
    plan: free
    branch: main
    rootDir: .
    autoDeploy: true
    envVars:
      - key: MB_JETTY_PORT
        value: "3000"
    disk:
      name: metabase-data
      mountPath: /app/data
